### ISSUE TITLE
Need help in adding Project Euler Solutions - Hacktoberfest

### ISSUE THREAD

**Issue by satyajitghana** [satyajitghana/project-euler#1]
Add solutions C/CPP/Python/Haskell/JS or any language, solutions for Project https://projecteuler.net/archives

Make sure to put the files in the right directory, and make sure to do some documentation, the website for the solutions is hosted on https://satyajitghana.github.io/project-euler

This should be a pretty good repository for Hacktoberfest :)

Add the solutions in a README in the correctly named folder, the README's are rendered on the website like this: https://satyajitghana.github.io/project-euler/problem-018/

**Comment by Maxtasy** [comment]
I'm working on problem #4.
