### ISSUE TITLE
Your projecteuler problems are not visible on the website now.

### ISSUE THREAD

**Issue by Yogisam72** [satyajitghana/project-euler#22]
It shows that the Data cant be shown now. Please look into it.
![probprojeuler](https://user-images.githubusercontent.com/48612683/94984886-a18f5a00-056e-11eb-8ebb-df1ecf4ec02b.PNG)

**Comment by satyajitghana** [comment]
Hi, i can view the problem https://projecteuler.net/problem=53

![image](https://user-images.githubusercontent.com/8092481/94997075-5d2fa880-05c6-11eb-9c59-317119636815.png)

Yes `solutions.md` in solutions folder is not updated, can you help in updating it ? or maybe writing a script that will search for solution folders and create solutions.md file ?

**Comment by satyajitghana** [comment]
I can add the script to run in github actions, so during deployment we can deploy all the added solutions to the website

**Comment by Yogisam72** [comment]
Okay maybe it was some issue on my end, it's working now.
